# Generated by Django 4.1.4 on 2023-03-29 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('accountnum', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CartIp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('img', models.ImageField(upload_to='uploads/')),
                ('price', models.IntegerField(default=0)),
                ('trending', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5, null=True)),
                ('available', models.IntegerField()),
                ('offer', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5)),
                ('outofstalk', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5)),
                ('agegroup', models.CharField(blank=True, choices=[('Man', 'Man'), ('Boy', 'Boy'), ('Woman', 'Woman'), ('Girl', 'Girl'), ('Baby', 'Baby')], max_length=200, null=True)),
                ('size', models.TextField(blank=True, choices=[('SM', 'SM'), ('L', 'L'), ('XL', 'XL'), ('All', 'All')], max_length=10, null=True)),
                ('category', models.ManyToManyField(to='boutique.category')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(null=True)),
                ('profile', models.ImageField(default='profile.svg', upload_to='')),
                ('phone', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.IntegerField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.item')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.locations')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('price', models.IntegerField(null=True)),
                ('checked', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.cartip')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.item')),
            ],
        ),
    ]
