# Generated by Django 4.1.4 on 2023-03-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_alter_category_title'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='locations',
            order_with_respect_to='city',
        ),
    ]
