# Generated by Django 4.1.4 on 2023-03-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_alter_locations_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'ordering': ['city']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='locations',
            order_with_respect_to=None,
        ),
    ]
