# Generated by Django 4.1.7 on 2023-04-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_alter_locations_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'ordering': ['city', 'area', 'shop']},
        ),
    ]
